:toc:
:icons: font
:source-highlighter: prettify
:project_id: neo4j excercise


= Using Spring Boot/Spring Batch/Spring Data Neo4j to ingest CSVs into Neo4j DB and build graph nodes + edges. 

== Instructions

=== Set up Neo4j (Docker / VM). 

```
docker run --publish=7474:7474 --publish=7687:7687 --volume=$HOME/neo4j/data:/data -e dbms.memory.heap.initial_size=1024m -e dbms.memory.heap.max_size=2048m  neo4j
```

=== Data Access

Orignal Data:
https://gist.github.com/maruthiprithivi/f11bf40b558879aca0c30ce76e7dec98[Banking - Customer & Transaction Data]

Please note, if you wishe to follow the exercise, please use the data in this repo as is (src/main/resource/data). Some minor modifications were done on the original data due to duplicate primary keys. 

=== Configuration (.properties file)

Change the uri, username and password for your own docker environment.
```
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=*************

spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

customerFile=data/customers.csv
transferFile=data/transfers.csv
purchaseFile=data/purchases.csv
```

=== Compile and package

```
mvn clean package
```

=== Run the application

==== Step 1. Ingest the CSVs

In step 1, we are simply ingesting the tables(CSVs) as nodes in neo4j. 

```
java -jar -Dspring.profiles.active=ingest target/neo4j-interview-exercise-0.0.1.jar
```

==== Step 2. Build Relationship(Edge)

In step 2, we are building the graph edges(relationships) by re-iterating through the Customer,Transfer and Purchase nodes. Although, programatically, this is achievable through interacting with Neo4jRepository interface, the write performance is extremely low this way. It will take more than 24 hours for our sample dataset. Hence we are creating a custom ItemReader and utilizing the power of Spring Batch. The job was done in less than 3 minutes! 

```
java -jar -Dspring.profiles.active=build target/neo4j-interview-exercise-0.0.1.jar
```

Throughout the exercise, we've managed to create the nodes and edges using entirely Spring Boot + Spring Batch + Spring Data Neo4j + POJOs without a single line of cipher. 

=== Query the graph 

Open browser at http://localhost:7474/browser/

